server:
  port: 8090

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  #数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: yzp230mysql
    url: jdbc:mysql://localhost:3306/qr_code?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowMultiQueries=true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 0
      maximum-pool-size: 20
      idle-timeout: 10000
      auto-commit: true
      connection-test-query: SELECT 1
  #日期格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  #redis
#  redis:
#    timeout: 10000ms
#    host: localhost
#    port: 6379
#    database: 0
#    password: 123456
#    lettuce:
#      pool:
#        max-active: 1024
#        max-wait: 10000ms
#        max-idle: 200
#        min-idle: 5

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: AUTO
      insert-strategy: not_empty
      update-strategy: not_empty
      table-prefix: p_